-- =====================================================================
-- 2026-08-17 — Unpack multi-URL song attachment / youtube records
-- =====================================================================
--
-- WHAT IS WRONG
-- -------------
-- `songs.attachments` is a JSON array of {url, name, ext, icon} records and
-- `songs.youtube` is a JSON array of URL strings. Two rows have SEVERAL urls
-- crammed into ONE array entry, joined with ", ":
--
--   song_1767451889865  "Away in Manger"                attachments[0] = 5 urls
--   song_1767452779910  "Hark the Herald Angel Sing"    attachments[0] = 2 urls
--   song_1767452779910  "Hark the Herald Angel Sing"    youtube[0]     = 2 urls
--
-- Every reader treats an entry as a single url, so Preview handed a
-- comma-joined blob to an iframe (it cannot load) and document counts
-- under-reported. "Away in Manger" also lists the same YouTube url twice, and
-- the same Google Doc twice inside its packed string.
--
-- Verified against all 51 rows on 2026-08-17: these are the ONLY affected
-- records. No other row has a packed or duplicated entry.
--
-- WHAT THIS DOES
-- --------------
-- Rewrites those three array values as properly separated entries. Nothing
-- else changes: no schema change, no column added or dropped, no RLS or policy
-- touched, no other row read or written.
--
-- The replacement values are LITERAL rather than computed by splitting in SQL.
-- Only two rows are affected and their correct contents are known exactly, so
-- a literal write is easier to review and cannot misfire on an edge case that
-- a regex would.
--
-- Each attachment's name/ext/icon was generated by the app's OWN classifier
-- (`parseFileUrl()` in Index.html), so the repaired rows are indistinguishable
-- from rows the app would write itself. That also corrects two records that
-- carried a stale `type: "GDOC"` field and claimed a Drive *file* was a Google
-- *Doc*; the repaired shape {url, name, ext, icon} matches the other 14
-- healthy attachment records in the table.
--
-- Duplicate urls are dropped: "Away in Manger" goes from 5 packed url tokens
-- to 4 distinct documents (one was listed twice), plus its second attachment,
-- for 5 distinct documents in total.
--
-- SAFETY
-- ------
-- * Runs inside a transaction — nothing is committed if any statement fails.
-- * Backs both rows up to `songs_attachment_repair_backup` FIRST, so the
--   change is reversible (rollback statement at the bottom of this file).
-- * Every UPDATE is guarded by a WHERE clause that only matches the packed
--   state, so re-running this file is a no-op rather than a second edit.
-- * The app does not need this migration to work: the reader-side fix in
--   `_sfExpandAttachments()` / `_sfExpandMedia()` already displays these rows
--   correctly. This repairs the stored data so every OTHER consumer — orders,
--   songbooks, exports — sees it correctly too.
--
-- HOW TO RUN
-- ----------
-- Paste into the Supabase SQL Editor and run. Expected result: 3 rows updated
-- (2 attachments + 1 youtube). The verification block at the end should report
-- zero remaining packed entries.
-- =====================================================================

BEGIN;

-- ---------------------------------------------------------------------
-- 1. Back up the affected rows before touching them
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS songs_attachment_repair_backup (
  id           text,
  title        text,
  attachments  jsonb,
  youtube      jsonb,
  backed_up_at timestamptz DEFAULT now()
);

-- Only ever back up ONCE. Without this guard a second run would append a
-- snapshot of the already-repaired rows, and the rollback below would then
-- restore whichever copy it happened to join against.
INSERT INTO songs_attachment_repair_backup (id, title, attachments, youtube)
SELECT s.id, s.title, s.attachments, s.youtube
FROM songs s
WHERE s.id IN ('song_1767451889865', 'song_1767452779910')
  AND NOT EXISTS (
    SELECT 1 FROM songs_attachment_repair_backup b WHERE b.id = s.id
  );

-- ---------------------------------------------------------------------
-- 2. "Away in Manger" — attachments: 2 entries (one packing 5 urls) -> 5
-- ---------------------------------------------------------------------
UPDATE songs
SET attachments = $json$[
  {"url":"https://drive.google.com/file/d/15WuTTYdtXK2KJnoVMCRWjVBsISg_Lc8F/view?usp=drive_link","name":"Google Drive File","ext":"file","icon":"fa-google-drive"},
  {"url":"https://docs.google.com/document/d/1LsM05phNJjTbfEUgusFhFUY2uFrFgajc/edit?usp=drive_link&ouid=106958184850014570488&rtpof=true&sd=true","name":"Google Doc","ext":"gdoc","icon":"fa-file-word"},
  {"url":"https://docs.google.com/document/d/1FqWhmFz6wzWbftqXpcpWKaPi28Q6TVBQkZKvlFRaqDA/edit?usp=drive_link","name":"Google Doc","ext":"gdoc","icon":"fa-file-word"},
  {"url":"https://docs.google.com/document/d/1tl6yP-YcskR1sYJFGw2GkFB6Q6_GGiKN/edit?usp=sharing&ouid=106958184850014570488&rtpof=true&sd=true","name":"Google Doc","ext":"gdoc","icon":"fa-file-word"},
  {"url":"https://docs.google.com/document/d/1k74Gkz0wjNbj116T6HZ95gWoO7X5YcUu/edit","name":"Google Doc","ext":"gdoc","icon":"fa-file-word"}
]$json$::jsonb
WHERE id = 'song_1767451889865'
  AND attachments::text LIKE '%, https%';   -- only while still packed

-- "Away in Manger" — youtube: the same video was listed twice
UPDATE songs
SET youtube = $json$[
  "https://www.youtube.com/watch?v=3dxzdsfJp2s",
  "https://www.youtube.com/watch?v=GjtYtBGrP6Y"
]$json$::jsonb
WHERE id = 'song_1767451889865'
  AND jsonb_array_length(youtube) = 3;  -- only while the duplicate is there

-- ---------------------------------------------------------------------
-- 3. "Hark the Herald Angel Sing" — attachments 1 -> 2, youtube 1 -> 2
-- ---------------------------------------------------------------------
UPDATE songs
SET attachments = $json$[
  {"url":"https://docs.google.com/document/d/1T_gbpWf52feBufbBem5hKGP6TTUmrkhY/edit?usp=drive_link&ouid=106958184850014570488&rtpof=true&sd=true","name":"Google Doc","ext":"gdoc","icon":"fa-file-word"},
  {"url":"https://drive.google.com/file/d/1UqKy4WhU4xmc2jz6VDzrU5AxGQSDPsPV/view?usp=drive_link","name":"Google Drive File","ext":"file","icon":"fa-google-drive"}
]$json$::jsonb
WHERE id = 'song_1767452779910'
  AND attachments::text LIKE '%, https%';

UPDATE songs
SET youtube = $json$[
  "https://www.youtube.com/watch?v=Z67EXPODXO8",
  "https://www.youtube.com/watch?v=-21i2R6b1qA"
]$json$::jsonb
WHERE id = 'song_1767452779910'
  AND youtube::text LIKE '%, https%';

COMMIT;

-- =====================================================================
-- VERIFICATION — run after the COMMIT. Both queries should return 0 rows.
-- =====================================================================

-- (a) No attachment entry may still hold more than one url.
SELECT s.id, s.title, elem->>'url' AS packed_url
FROM songs s, jsonb_array_elements(s.attachments) elem
WHERE elem->>'url' LIKE '%, %';

-- (b) No youtube entry may still hold more than one url.
SELECT s.id, s.title, elem AS packed_url
FROM songs s, jsonb_array_elements(s.youtube) elem
WHERE elem::text LIKE '%, %';

-- (c) Sanity: the two repaired rows should now read 5/2 and 2/2.
SELECT id, title,
       jsonb_array_length(attachments) AS attachment_count,
       jsonb_array_length(youtube)     AS youtube_count
FROM songs
WHERE id IN ('song_1767451889865', 'song_1767452779910');
-- expected:
--   song_1767451889865  Away in Manger              5  2
--   song_1767452779910  Hark the Herald Angel Sing  2  2

-- =====================================================================
-- ROLLBACK — only if the repair needs undoing. Restores from the backup
-- table written in step 1.
-- =====================================================================
-- UPDATE songs s
-- SET attachments = b.attachments,
--     youtube     = b.youtube
-- FROM songs_attachment_repair_backup b
-- WHERE s.id = b.id;
--
-- Once the repair is confirmed good, the backup table can be dropped:
-- DROP TABLE songs_attachment_repair_backup;
