'use client';

import { Suspense, useEffect, useRef, useState } from 'react';
import { useSearchParams } from 'next/navigation';
import { fetchPlayers, fetchSectionScores, fetchSessionByCode, fetchSong, joinSession, savePlayerRoundStats, subscribeToSession, updatePlayerLobbyState } from '@/lib/vocal-hero/supabaseClient';
import { PitchEngine } from '@/lib/vocal-hero/pitchEngine';
import { ScoreEngine } from '@/lib/vocal-hero/scoreEngine';
import type { GameSession, SectionScore, SessionPlayer, Song, SongNote } from '@/lib/vocal-hero/types';
import { SatbLane } from '../SatbLane';
import { isGuideMelody, playableNotes, playablePart } from '@/lib/vocal-hero/songData';
import { measureServerClockOffset } from '@/lib/vocal-hero/clock';

const VOICES = ['Soprano', 'Alto', 'Tenor', 'Bass'];
const COLOURS = ['#ff60bc', '#a965ff', '#22d3ee', '#ffbd45'];

export default function PhonePage() { return <Suspense fallback={<main className="min-h-screen bg-[#030611]" />}><PhoneGame /></Suspense>; }

function PhoneGame() {
  const params = useSearchParams();
  const [room, setRoom] = useState((params.get('room') ?? '').toUpperCase());
  const [name, setName] = useState(''); const [partIndex, setPartIndex] = useState(0);
  const [session, setSession] = useState<GameSession | null>(null); const [song, setSong] = useState<Song | null>(null); const [player, setPlayer] = useState<SessionPlayer | null>(null);
  const [players, setPlayers] = useState<SessionPlayer[]>([]); const [sections, setSections] = useState<SectionScore[]>([]); const [error, setError] = useState('');
  const [mic, setMic] = useState<'unknown' | 'checking' | 'ready' | 'blocked'>('unknown'); const [now, setNow] = useState(Date.now()); const [clockOffset, setClockOffset] = useState(0);
  const [pitch, setPitch] = useState(0); const [score, setScore] = useState(0); const [hits, setHits] = useState<Record<string, boolean>>({}); const [fullBoard, setFullBoard] = useState(false);
  const pitchRef = useRef<PitchEngine | null>(null); const scoreRef = useRef<ScoreEngine | null>(null); const unsubRef = useRef<(() => void) | null>(null); const startedRef = useRef(false); const elapsedRef = useRef(0); const phaseRef = useRef('Waiting'); const lastPitchPaintRef = useRef(0); const cuePlayedRef = useRef(false);
  useEffect(() => () => { pitchRef.current?.stop(); void scoreRef.current?.stop(); unsubRef.current?.(); }, []);
  useEffect(() => { if (!session) return; const interval = window.setInterval(() => { setNow(Date.now()); void fetchPlayers(session.id).then(setPlayers); void fetchSectionScores(session.id).then(setSections).catch(() => setSections([])); }, 900); return () => clearInterval(interval); }, [session]);
  useEffect(() => { if (session?.status !== 'playing') return; let frame = 0, last = 0; const tick = (time: number) => { if (time - last > 33) { setNow(Date.now()); last = time; } frame = requestAnimationFrame(tick); }; frame = requestAnimationFrame(tick); return () => cancelAnimationFrame(frame); }, [session?.status]);
  const timeline = timelineFor(session, now + clockOffset); const notes = song ? playableNotes(song) : []; const part = song ? playablePart(song, partIndex) : null;
  useEffect(() => { elapsedRef.current = timeline.songElapsed; phaseRef.current = timeline.phase; }, [timeline.phase, timeline.songElapsed]);

  async function startPitchTracking() { if (pitchRef.current?.isRunning) return true; const engine = new PitchEngine({ bufferSize: 1024, confidenceThreshold: .72, smoothing: .35, onPitch: sample => { if (performance.now() - lastPitchPaintRef.current > 33) { setPitch(sample.frequency); lastPitchPaintRef.current = performance.now(); } if (phaseRef.current === 'live' && sample.confidence > .78) scoreRef.current?.scorePitch(sample.frequency, Math.max(0, elapsedRef.current)); } }); pitchRef.current = engine; try { await engine.start(); setMic('ready'); return true; } catch { pitchRef.current = null; setMic('blocked'); return false; } }
  useEffect(() => { if (timeline.phase !== 'Lead-in · listen' || cuePlayedRef.current || !song) return; cuePlayedRef.current = true; const first = notes.filter(note => note.part === partIndex || note.part === -1).sort((a, b) => a.start - b.start).slice(0, 2); if (!first.length) return; const context = new AudioContext({ latencyHint: 'interactive' }); first.forEach((note, index) => { const oscillator = context.createOscillator(), gain = context.createGain(), at = context.currentTime + .08 + index * .65; oscillator.frequency.value = PitchEngine.midiToHz(note.midi); gain.gain.setValueAtTime(.0001, at); gain.gain.exponentialRampToValueAtTime(.16, at + .03); gain.gain.exponentialRampToValueAtTime(.0001, at + .55); oscillator.connect(gain).connect(context.destination); oscillator.start(at); oscillator.stop(at + .58); }); window.setTimeout(() => void context.close(), 1800); }, [notes, partIndex, song, timeline.phase]);
  useEffect(() => { if (!session || !song || !player || !part || session.status !== 'playing' || startedRef.current) return; startedRef.current = true; const scorer = new ScoreEngine({ part, partIndex, notes, songDuration: song.duration, playerId: player.id, sessionId: session.id, onScoreUpdate: (_, total) => setScore(total), onNoteResult: result => setHits(current => ({ ...current, [result.noteId]: result.points > 0 })) }); scoreRef.current = scorer; scorer.start(); void startPitchTracking(); }, [notes, part, partIndex, player, session, song]);
  useEffect(() => { if (session?.status !== 'playing' || !player) return; const interval = setInterval(() => { const stats = scoreRef.current?.stats; if (stats) void savePlayerRoundStats({ session_id: session.id, player_id: player.id, score: scoreRef.current?.currentTotal ?? 0, accuracy: stats.accuracy, notes_attempted: stats.attempted, notes_hit: stats.hit }); }, 3000); return () => clearInterval(interval); }, [player, session?.id, session?.status]);
  useEffect(() => { if (session?.status !== 'ended' || !player || !scoreRef.current) return; pitchRef.current?.stop(); const stats = scoreRef.current.stats; void scoreRef.current.stop().then(() => savePlayerRoundStats({ session_id: session.id, player_id: player.id, score, accuracy: stats.accuracy, notes_attempted: stats.attempted, notes_hit: stats.hit })); }, [player, score, session?.status]);
  async function join(event: React.FormEvent) { event.preventDefault(); if (!room || !name.trim()) { setError('Enter your room code and name.'); return; } try { const next = await fetchSessionByCode(room); if (!next || next.status === 'ended') throw new Error('That room is unavailable.'); const nextSong = await fetchSong(next.song_id); if (!nextSong) throw new Error('Song not found.'); const nextPlayer = await joinSession(next.id, name.trim(), partIndex); setClockOffset(await measureServerClockOffset().catch(() => 0)); unsubRef.current = subscribeToSession(next.id, setSession); setSession(next); setSong(nextSong); setPlayer(nextPlayer); setPlayers(await fetchPlayers(next.id)); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to join.'); } }
  async function testMic() { if (!player) return; setMic('checking'); await startPitchTracking(); await updatePlayerLobbyState(player.id, { ready_at: player.ready_at ?? null, mic_status: pitchRef.current?.isRunning ? 'ready' : 'blocked' }); }
  async function readyUp() { if (!player) return; const readyAt = player.ready_at ? null : new Date().toISOString(); await updatePlayerLobbyState(player.id, { ready_at: readyAt, mic_status: mic === 'ready' ? 'ready' : 'unknown' }); setPlayer({ ...player, ready_at: readyAt }); }
  if (!session) return <Join room={room} setRoom={setRoom} name={name} setName={setName} part={partIndex} setPart={setPartIndex} error={error} join={join} />;
  if (session.status === 'lobby') return <PhoneLobby song={song!} code={session.room_code} part={partIndex} players={players} player={player} mic={mic} testMic={testMic} ready={readyUp} />;
  if (session.status === 'ended') return <PhoneEnd score={score} sections={sections} part={partIndex} />;
  if (timeline.phase !== 'live') return <PhoneCountdown song={song!} part={partIndex} phase={timeline.phase} mic={mic} />;
  return <PhoneLive song={song!} notes={notes} guide={isGuideMelody(notes)} part={partIndex} elapsed={timeline.songElapsed} pitch={pitch} score={score} hits={hits} sections={sections} mic={mic} fullBoard={fullBoard} setFullBoard={setFullBoard} />;
}

function PhoneBrand() { return <b className="text-xl">VOCAL<span className="text-fuchsia-400">Hero</span></b>; }
function PhoneShell({ children }: { children: React.ReactNode }) { return <main className="vh-app min-h-screen px-4 pb-6 pt-5 text-slate-100"><header className="flex items-center justify-between border-b border-white/10 pb-4"><span className="text-slate-400">☰</span><PhoneBrand /><span className="text-slate-400">?</span></header>{children}</main>; }
function Join({ room, setRoom, name, setName, part, setPart, error, join }: { room: string; setRoom: (v: string) => void; name: string; setName: (v: string) => void; part: number; setPart: (v: number) => void; error: string; join: (event: React.FormEvent) => void }) { return <PhoneShell><form onSubmit={join} className="mx-auto mt-10 max-w-md vh-panel p-5"><p className="text-center text-xs tracking-[.2em] text-fuchsia-300">JOIN LOBBY</p><h1 className="mt-3 text-center text-3xl font-black">Sing your part.</h1><label className="mt-6 block text-xs text-slate-400">Room code<input value={room} onChange={e => setRoom(e.target.value.toUpperCase())} maxLength={5} className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-center font-mono text-2xl tracking-[.25em]" /></label><label className="mt-4 block text-xs text-slate-400">Nickname<input value={name} onChange={e => setName(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-base" /></label><p className="mt-5 text-xs tracking-[.15em] text-slate-400">CHOOSE YOUR PART</p><div className="mt-2 grid grid-cols-2 gap-2">{VOICES.map((voice, index) => <button type="button" key={voice} onClick={() => setPart(index)} className="rounded-xl border p-3 text-left" style={{ borderColor: part === index ? COLOURS[index] : '#ffffff18', background: part === index ? `${COLOURS[index]}18` : '#07111d' }}><b className="text-2xl" style={{ color: COLOURS[index] }}>{voice[0]}</b><span className="ml-2 text-sm">{voice}</span></button>)}</div>{error && <p className="mt-4 text-sm text-rose-300">{error}</p>}<button className="vh-start-button mt-6 w-full">JOIN LOBBY</button></form></PhoneShell>; }
function PhoneLobby({ song, code, part, players, player, mic, testMic, ready }: { song: Song; code: string; part: number; players: SessionPlayer[]; player: SessionPlayer | null; mic: string; testMic: () => void; ready: () => void }) { return <PhoneShell><div className="mt-5 text-center"><p className="text-sm text-slate-300">{song.title}</p><p className="mt-1 text-xs text-slate-500">{song.artist || 'Vocal Hero arrangement'}</p><p className="mt-4 text-xs text-slate-400">ROOM CODE</p><p className="font-mono text-3xl font-bold tracking-[.25em] text-[#ffd15c]">{code}</p></div><p className="mt-7 text-center text-xs tracking-[.18em] text-slate-400">CHOOSE YOUR PART</p><div className="mt-3 grid grid-cols-2 gap-2">{VOICES.map((voice, index) => <div key={voice} className="rounded-xl border p-3" style={{ borderColor: index === part ? COLOURS[index] : '#ffffff16', background: index === part ? `${COLOURS[index]}14` : '#07111d' }}><b style={{ color: COLOURS[index] }}>{voice[0]} <span className="ml-1 text-sm">{voice}</span></b><p className="mt-2 text-xs text-slate-400">{players.filter(item => item.part_index === index).length} players</p></div>)}</div><div className="mt-5 rounded-2xl border border-white/10 bg-black/20 p-4"><p className="text-xs text-slate-400">MIC CHECK</p><button onClick={testMic} className="mt-2 text-sm text-emerald-300">● {mic === 'ready' ? 'Microphone detected' : 'Test microphone'}</button></div><button onClick={ready} className="vh-start-button mt-5 w-full">✓ {player?.ready_at ? 'I’M READY' : 'TAP WHEN READY'}</button></PhoneShell>; }
function PhoneCountdown({ song, part, phase, mic }: { song: Song; part: number; phase: string; mic: string }) { const number = Number(phase.match(/(\d+)/)?.[1] ?? 0); return <PhoneShell><p className="mt-6 text-center text-sm">{song.title}</p><p className="mt-2 text-center text-xs text-slate-400">YOUR PART</p><h1 className="text-center text-2xl font-black" style={{ color: COLOURS[part] }}>{VOICES[part].toUpperCase()} {VOICES[part][0]}</h1><div className="mx-auto mt-12 grid h-60 w-60 place-items-center rounded-full border-2 border-fuchsia-400 bg-fuchsia-400/[.08] shadow-[0_0_55px_#ec4899]"><div className="text-center"><p className="text-8xl font-black text-fuchsia-300">{number || '•'}</p><p className="mt-2 text-sm tracking-[.2em] text-fuchsia-200">GET READY</p></div></div><div className="mt-12 text-center"><p className="text-4xl text-fuchsia-300">◉</p><p className="mt-2 text-sm text-emerald-300">{mic === 'ready' ? 'READY' : 'MIC CHECK'}</p></div><p className="mt-7 text-center text-sm text-slate-300">◉ Eyes on your part <span className="mx-2 text-slate-600">|</span> ≋ Breathe in</p></PhoneShell>; }
function PhoneLive({ song, notes, guide, part, elapsed, pitch, score, hits, sections, mic, fullBoard, setFullBoard }: { song: Song; notes: SongNote[]; guide: boolean; part: number; elapsed: number; pitch: number; score: number; hits: Record<string, boolean>; sections: SectionScore[]; mic: string; fullBoard: boolean; setFullBoard: (value: boolean) => void }) { const lyric = notes.find(note => (note.part === part || note.part === -1) && elapsed >= note.start && elapsed < note.end)?.lyric; const team = sections.find(section => section.part_index === part); return <PhoneShell><div className="mt-5 flex items-center justify-between"><div><p className="text-xs text-slate-400">{song.title}</p><b style={{ color: COLOURS[part] }}>{VOICES[part].toUpperCase()} TEAM</b></div><div className="text-right"><p className="text-3xl font-black text-fuchsia-300">{score.toLocaleString()}</p><p className="text-[10px] tracking-[.16em] text-slate-500">PERSONAL SCORE</p></div></div><section className="mt-5 rounded-2xl border border-white/10 bg-black/20 p-4 text-center"><p className="min-h-8 text-2xl font-bold">{lyric || 'Listen · breathe · prepare'}</p></section><div className="mt-4"><SatbLane partIndex={guide ? -1 : part} partName={guide ? 'Melody guide' : VOICES[part]} colour={guide ? '#ff60bc' : COLOURS[part]} elapsed={elapsed} notes={notes} pitchHz={pitch} hitNotes={hits} lookAheadSeconds={4} showLyrics={false} /></div><div className="mt-4 grid grid-cols-2 gap-3"><div className="vh-panel p-3"><p className="text-xs text-slate-400">TEAM ACCURACY</p><b className="text-xl">{Math.round(team?.accuracy ?? 0)}%</b></div><div className="vh-panel p-3"><p className="text-xs text-slate-400">MIC</p><b className="text-xl text-emerald-300">{mic === 'ready' ? 'READY' : 'CHECK'}</b></div></div>{!guide && <button onClick={() => setFullBoard(!fullBoard)} className="vh-outline-button mt-4 w-full">{fullBoard ? 'Return to my part' : 'Show full choir board'}</button>}{fullBoard && <div className="mt-3 space-y-2">{VOICES.map((voice, index) => <SatbLane key={voice} compact partIndex={index} partName={voice} colour={COLOURS[index]} elapsed={elapsed} notes={notes} pitchHz={index === part ? pitch : undefined} hitNotes={hits} lookAheadSeconds={4} />)}</div>}</PhoneShell>; }
function PhoneEnd({ score, sections, part }: { score: number; sections: SectionScore[]; part: number }) { return <PhoneShell><div className="mt-28 text-center"><p className="text-xs tracking-[.25em] text-fuchsia-300">SESSION COMPLETE</p><h1 className="mt-3 text-4xl font-black">Every voice counted.</h1><p className="mt-8 text-7xl font-black text-cyan-300">{score}</p><p className="mt-1 text-slate-400">Your personal score</p><p className="mt-7">{VOICES[part]} accuracy <b className="ml-2" style={{ color: COLOURS[part] }}>{Math.round(sections.find(section => section.part_index === part)?.accuracy ?? 0)}%</b></p></div></PhoneShell>; }
function timelineFor(session: GameSession | null, now: number) { if (!session?.playback_starts_at) return { phase: 'Waiting', songElapsed: 0 }; const delta = now - new Date(session.playback_starts_at).getTime(); const countdown = session.countdown_seconds ?? 5, lead = session.lead_in_seconds ?? 2; if (delta < 0) return { phase: `Starts in ${Math.ceil(-delta / 1000)}`, songElapsed: 0 }; const seconds = delta / 1000; if (seconds < countdown) return { phase: `Count-in ${countdown - Math.floor(seconds)}`, songElapsed: 0 }; if (seconds < countdown + lead) return { phase: 'Lead-in · listen', songElapsed: 0 }; return { phase: 'live', songElapsed: seconds - countdown - lead }; }
