import { NextResponse } from 'next/server';
import { getServiceClient } from '@/lib/vocal-hero/supabaseClient';

export async function POST(request: Request) {
  try {
    const body = await request.json() as { sessionId?: string; countdownSeconds?: number; leadInSeconds?: number };
    if (!body.sessionId) return NextResponse.json({ error: 'sessionId is required' }, { status: 400 });
    const countdown = Math.max(3, Math.min(10, Number(body.countdownSeconds) || 5));
    const leadIn = Math.max(1, Math.min(8, Number(body.leadInSeconds) || 2));
    // This time is generated by the server—not the host computer—and gives
    // Realtime/polling clients ample time to receive the scheduled start.
    const playbackStartsAt = new Date(Date.now() + 5000).toISOString();
    const { data, error } = await getServiceClient()
      .from('vh_game_sessions')
      .update({
        status: 'playing',
        started_at: new Date().toISOString(),
        playback_starts_at: playbackStartsAt,
        countdown_seconds: countdown,
        lead_in_seconds: leadIn,
      })
      .eq('id', body.sessionId)
      .select()
      .single();
    if (error) throw error;
    return NextResponse.json(data, { headers: { 'Cache-Control': 'no-store, max-age=0' } });
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Unable to schedule the session.';
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
